SchoolProject/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolProject.Models;
using SchoolProject.Repository;

namespace SchoolProject.Controllers
{
    public class CourseController : Controller
    {
        private readonly ICourseRepo _ICs;
        private readonly ITeacherRepo _ITch;
        public CourseController(ICourseRepo ICs ,ITeacherRepo ITch) { _ICs = ICs; _ITch = ITch; }

        [HttpGet]
        public ActionResult Index()
        {
            List<Course> courses = _ICs.GetAllCourses();
            return View(courses);
        }
        [HttpGet]
        public ViewResult Create()
        {
            List<Teacher> teachers= _ITch.GetAllTeachers();
            return View(teachers);
        }
        [HttpPost]
        public ActionResult Create(Course course)
        {
            if (course != null)
            {
                _ICs.Create(course);
            }
            List<Course> courses = _ICs.GetAllCourses();
            return View("Index",courses);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (id > 0)
            {
                _ICs.Delete(id);
            }
            List<Course> courses = _ICs.GetAllCourses();
            return View("Index", courses);
        }
    }
}

SchoolProject/Controllers/RoomController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolProject.Models;
using SchoolProject.Repository;

namespace SchoolProject.Controllers
{
    public class RoomController : Controller
    {
        private readonly IRoomRepo _IRm;
        public RoomController(IRoomRepo IRm) { _IRm = IRm; }

        [HttpGet]
        public ActionResult Index()
        {
            List<Room> rooms = _IRm.GetAllRooms();
            return View(rooms);
        }
        [HttpGet]
        public ViewResult Create()
        {

            return View();
        }
        [HttpPost]
        public ActionResult Create(Room room)
        {
            if (room != null)
            {
                _IRm.Create(room);
            }
            List<Room> rooms = _IRm.GetAllRooms();
            return View("Index",rooms);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (id > 0)
            {
                _IRm.Delete(id);
            }
            List<Room> rooms = _IRm.GetAllRooms();
            return View("Index",rooms);
        }
    }
}

SchoolProject/Controllers/StudentController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolProject.Models;
using SchoolProject.Models.VMs;
using SchoolProject.Repository;
using Microsoft.AspNetCore.Hosting;

namespace SchoolProject.Controllers
{
    public class StudentController : Controller
    {
        private readonly IStudentRepo _studentRepo;
        private readonly ICourseRepo _courseRepo;
        private readonly Microsoft.AspNetCore.Hosting.IHostingEnvironment _environment;
        public StudentController(IStudentRepo studentRepo,ICourseRepo courseRepo, Microsoft.AspNetCore.Hosting.IHostingEnvironment environment)
        {
            _studentRepo = studentRepo;
            _courseRepo = courseRepo;
            _environment = environment;
        }

        //list of students
        [HttpGet]
        public ActionResult Index()
        {
            List<Student> StdLst= _studentRepo.GetAllStudents();
            return View(StdLst);
        }
        //render the creation view
        [HttpGet]
        public ViewResult Create()
        {
            return View();
        }
        [HttpPost]
        public ActionResult Create(Student student,IFormFile StudentPhoto)
        {
            Guid guid = Guid.NewGuid();
            var wwwrootPath = _environment.WebRootPath + "/StudentPhotos/";
            string fullPath = System.IO.Path.Combine(wwwrootPath,guid+ StudentPhoto.FileName);
            using (var fileStream = new FileStream(fullPath, FileMode.Create))
            {
                StudentPhoto.CopyTo(fileStream);
            };
            student.PhotonName = guid + StudentPhoto.FileName;
                _studentRepo.Create(student);
            List<Student> StdLst = _studentRepo.GetAllStudents();
            return View("Index",StdLst);
        }

        public ViewResult Delete(int id)
        {
            if (id > 0)
            {
                _studentRepo.Delete(id);
            }
           List<Student> StdLst = _studentRepo.GetAllStudents();
            return View("Index",StdLst);
        }
        [HttpGet]
        public ActionResult Register()
        {
            StudentCourseVM studentCourseVM = new StudentCourseVM();
            studentCourseVM.Courses = _courseRepo.GetAllCourses();
            studentCourseVM.Students = _studentRepo.GetAllStudents();
            return View(studentCourseVM);
        }
        [HttpPost]
        public ActionResult Register(int studentId, int courseId)
        {
            _studentRepo.Register(studentId, courseId);
           return RedirectToAction("Register");
        }
    }
}

SchoolProject/Controllers/TeacherController.cs
using Microsoft.AspNetCore.Mvc;
using SchoolProject.Context;
using SchoolProject.Models;
using SchoolProject.Repository;

namespace SchoolProject.Controllers
{
    public class TeacherController : Controller
    {
        private readonly ITeacherRepo _ITch;
        public TeacherController(ITeacherRepo ITch) { _ITch = ITch; }

        [HttpGet]
        public ActionResult Index()
        {
            List<Teacher> teachers = _ITch.GetAllTeachers();   
            return View(teachers);
        }
        [HttpGet]
        public ViewResult Create()
        {
            
            return View();
        }
        [HttpPost]
        public ActionResult Create(Teacher teacher)
        {
            if (teacher != null)
            {
                _ITch.Create(teacher);
            }
            List<Teacher> teachers = _ITch.GetAllTeachers();
            return View("Index",teachers);
        }
        [HttpGet]
        public ActionResult Delete(int id)
        {
            if (id > 0)
            {
                _ITch.Delete(id);
            }
            List<Teacher> teachers = _ITch.GetAllTeachers();
            return View("Index",teachers);
        }

    }
}

SchoolProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SchoolProject</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/SchoolProject.styles.css" asp-append-version="true" />
    <link href="~/css/formdesign.css" rel="stylesheet" />
    <link href="~/css/table.css" rel="stylesheet" />
    <link href="~/css/custom.css" rel="stylesheet" />
    <link href="~/css/stylesheet.css" rel="stylesheet" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-lg navbar-light bg-light shadow-sm">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SchoolProject</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNav">
                    <ul class="navbar-nav ms-auto">
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Index">Students</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Teacher" asp-action="Index">Teachers</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Course" asp-action="Index">Courses</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Room" asp-action="Index">Rooms</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link" asp-area="" asp-controller="Student" asp-action="Register">Register Student</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container my-4">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/custom.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>

</html>